server:
  port: 8090
spring:
  #  security:
  #    basic:
  #      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://172.16.4.12:3306/activiti?characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/act?characterEncoding=utf8
    username: root
    password: root

  activiti:
    # 启动是否更新表解耦股
    database-schema-update: true
    #自动部署认证
    check-process-definitions: false
    #流程描述文件的前缀(路径)
    process-definition-location-prefix: classpath:/processes/
    #文件后缀
    #process-definition-location-suffixes: .bpmn
    history-level: full
    #检测身份信息表是否存在
    db-identity-used: true

  thymeleaf:
    cache: false


logging:
  level:
    root: debug