spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&nullCatalogMeansCurrent=true&serverTimezone=GMT&useSSL=false
    username: root
    password: root

  activiti:
    # 启动是否更新表解耦股
    database-schema-update: true
    #自动部署认证
    check-process-definitions: true
    #流程描述文件的前缀(路径)
    process-definition-location-prefix: classpath:/processes/
    #文件后缀
    #process-definition-location-suffixes: .bpmn
    history-level: full
    #检测身份信息表是否存在
    db-identity-used: false
  liquibase:
    enabled: false
    change-log: classpath:changelog.xml
  contentstorage:
    fs:
      rootFolder: /data
      createRoot: true
      depth: 4
      blockSize: 1024

logging:
  level:
    root: info